export const USER_SIGNUP_START = "USER_SIGNUP_START";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const SEND_VERIFY_CODE_START = "SEND_VERIFY_CODE_START";
export const SEND_VERIFY_CODE_SUCCESS = "SEND_VERIFY_CODE_SUCCESS";
export const SEND_VERIFY_CODE_FAIL = "SEND_VERIFY_CODE_FAIL";

export const VERIFY_CODE_START = "VERIFY_CODE_START";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_FAIL = "VERIFY_CODE_FAIL";

export const CREATE_EVENT_START = "CREATE_EVENT_START";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_END = "CREATE_EVENT_END";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const FETCH_ALL_EVENTS_START = "FETCH_ALL_EVENTS_START";
export const FETCH_ALL_EVENTS_SUCCESS = "FETCH_ALL_EVENTS_SUCCESS";
export const FETCH_ALL_EVENTS_FAIL = "FETCH_ALL_EVENTS_FAIL";

export const FETCH_SINGLE_EVENT_START = "FETCH_SINGLE_EVENT_START";
export const FETCH_SINGLE_EVENT_SUCCESS = "FETCH_SINGLE_EVENT_SUCCESS";
export const FETCH_SINGLE_EVENT_FAIL = "FETCH_SINGLE_EVENT_FAIL";

export const FOLLOW_USER = "FOLLOW_USER";
export const FOLLOW_USER_ERROR = "FOLLOW_USER_ERROR";

export const FETCH_ALL_FRIEND_REQUEST_START = "FETCH_ALL_FRIEND_REQUEST_START";
export const FETCH_ALL_FRIEND_REQUEST_SUCCESS =
  "FETCH_ALL_FRIEND_REQUEST_SUCCESS";
export const FETCH_ALL_FRIEND_REQUEST_FAIL = "FETCH_ALL_FRIEND_REQUEST_FAIL";

export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_FRIEND_REQUEST_FAIL = "ACCEPT_FRIEND_REQUEST_FAIL";

export const FOLLOW_EVENT_SUCCESS = "FOLLOW_EVENT_SUCCESS";
export const FOLLOW_EVENT_ERROR = "FOLLOW_EVENT_ERROR";

export const FETCH_ALL_USER_FOLLOWING_SUCCESS =
  "FETCH_ALL_USER_FOLLOWING_SUCCESS";
export const FETCH_ALL_USER_FOLLOWING_FAIL = "FETCH_ALL_USER_FOLLOWING_ERROR";
